name: AquariaMasters
favicon: null
layout_spectrum: 0.37748
typography_spectrum: 0.06396
title: WATER = LIFE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#496571'
    - '#793f33'
    - '#7d9dce'
    - '#96e4e8'
  brandStrength: 0.21597061934880912
  lightness: 0.8862236372660846
  saturation: 0.5196404710877687
  rhythmicContrast: 0.3180573263671249
purpose: []
