name: AquariaMasters
favicon: null
layout_spectrum: 0.50721
typography_spectrum: 0.07477
title: Aquaria Masters @ TheGrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0071ba'
    - '#74b3d8'
    - '#408fc1'
    - '#52537f'
  brandStrength: 0.21597061934880912
  lightness: 0.8862236372660846
  saturation: 0.5196404710877687
  rhythmicContrast: 0.3180573263671249
purpose: []
